### ISSUE TITLE
Rename UK_Reports

### ISSUE THREAD

**Issue by dreispt** [OCA/l10n-united-kingdom#2]
I'm afraid the module name is not aligned with the common practice.
I suggest renaming it at least to `l10n_uk_report`, but a more specific name would be helpful.
If accounting related `l10n_uk_account_report` would be more helpful.

**Comment by nuria-opusvl** [comment]
No problem, I'll do that.

On 04/09/15 09:27, Daniel Reis wrote:

> I'm afraid the module name is not aligned with the common practice.
> I suggest renaming it at least to |l10n_uk_report|, but a more 
> specific name would be helpful.
> If accounting related |l10n_uk_account_report| would be more helpful.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/OCA/l10n-united-kingdom/issues/2.

## 

N. Arranz-Velazquez
OpusVL Odoo Specialist Team (OOST)
Product Owner

OpusVL
Drury House
Drury Lane
Rugby
CV21 3DE

T: 01788 298 450
W: www.opusvl.com

**Comment by dreispt** [comment]
Closed by #3
